channels:
  - conda-forge
dependencies:
  - python=3.9
  - compilers
  - cmake
  - scikit-build
  - pyyaml
  - opencv
  - mesa-libgl-devel-cos7-x86_64 
  - mesa-dri-drivers-cos7-x86_64 
  - libxcb
  - glew
  - glfw
  - librealsense
  - quaternion
