
intrinsics_color:
  fu: 615.2
  fv: 615.2
  ppu: 324.0
  ppv: 237.0
  width: 640
  height: 480

intrinsics_depth:
  fu:  423.893
  fv:  423.893
  ppu: 424.877
  ppv: 226.946
  width:  848
  height: 480

quat_d_c_xyzw: [-0.001, -0.003, -0.004, 1.000] 
trans_d_c: [-0.015, 0, 0]